docs: remove walls of text from templates
Geek-Collectors-Network/geek-collectors-network pull request #85
Opened 2024-02-20 22:11 UTC by FoRVaiS

## Summary
Remove explanations from templates and save them into an archive in the wiki.

2024-02-21 01:46 UTC, tgrigoruk commented
May I suggest something in between - just a short description of what each section should be about. (Also I prefer h3 over h2, the line is visual clutter to me).
For example (first two sections of PR template):

### Summary

_Concise overview of changes being made_

### Retrospective

_Challenges overcome, insights made, strategies learned, etc._

2024-02-24 23:17 UTC, tgrigoruk commented on .github/PULL_REQUEST_TEMPLATE.md
May I suggest something in between - just a short description of what each section should be about. (Also I prefer h3 over h2, the line is visual clutter to me).
For example (first two sections of PR template):

### Summary

_Concise overview of changes being made_

### Retrospective

_Challenges overcome, insights made, strategies learned, etc._

2024-02-24 23:20 UTC, tgrigoruk requested changes
May I suggest something in between - just a short description of what each section should be about. (Also I prefer h3 over h2, the horizontal line that h2 creates is visual clutter to me).
For example (first two sections of PR template):

### Summary

_Concise overview of changes being made_

### Retrospective

_Challenges overcome, insights made, strategies learned, etc._

2024-03-05 00:36 UTC, tgrigoruk commented
I'm not sure if any changes were made since my last comment. If you don't agree with keeping a single concise line of text for each section, fine, but I'm pretty adamant about using ### over ##. There's enough horizontal lines on any given github page as it is.

2024-03-06 11:09 UTC, FoRVaiS commented
@tgrigoruk Changes made.

### Summary
 - Use h3 instead of h2
 - Add one-line descriptions for each section
 - Removed "solution" section from "new task" template

2024-03-06 17:10 UTC, tgrigoruk approved these changes

2024-03-06 17:41 UTC, merged