30 add login page client side input validation
Geek-Collectors-Network/geek-collectors-network pull request #96
Opened 2024-02-21 23:39 UTC by rhysmah

## Summary
Provide a brief overview of the changes made in this pull request. Be specific about what has been added, removed, or modified within the project. This section should be concise but informative enough to give readers a clear understanding of what to expect when reviewing your changes.

**Example**:
This pull request adds a new feature that allows users to create custom dashboards by selecting specific widgets from a predefined list.

## Retrospective
Share any insights or lessons learned during the development process that may be helpful for others to benefit from. This can include challenges faced, solutions found, or any other relevant information that can help improve future development efforts.

This section is **omitable** if there is no relevant information.

**Example**:
During development, we encountered some difficulty in designing a UI for creating custom dashboards that was both intuitive and functional across various screen sizes and devices. However, after experimenting with different layout options and conducting user testing sessions, we were able to arrive at a design that met our requirements while also providing a positive user experience.

## Reviewer's Notes
Provide any additional information that reviewers may need to know before testing your changes. This can include specific scenarios to test, known issues or limitations, or any other relevant details that can help ensure a thorough review process.

This section is **omitable** if there is no relevant information.

**Example**:
When testing this feature, please ensure that you test it on multiple devices (e.g., desktop, tablet, mobile) to verify its responsiveness and functionality across various screen sizes.

Additionally, please note that there is currently a known issue where users may experience slow performance when creating a dashboard with a large number of widgets; this will be addressed in a future update.

## Testing
Provide clear instructions for reviewers to test your changes effectively. This can include specific scenarios to test, expected results, or any other relevant details that can help ensure a thorough review process. If possible, include screenshots or other visual aids to illustrate your points.

**Example**:
Test the creation of custom Dashboard using Widgets
1. Open our application in a web browser on a desktop computer.
2. Navigate to the "Create Dashboard" page within the application.
3. Select a few widgets from the predefined list to add to your dashboard.
4. Arrange the widgets on the canvas as desired.
5. Save your dashboard by clicking the "Save Dashboard" button.

2024-02-22 20:58 UTC, toco-t requested changes
Everything looks great except for a minor typo. Well done!

Also, I've just merged some changes so please fetch them :)

2024-02-22 20:58 UTC, toco-t commented on apps/frontend/src/components/LoginForm.tsx
> +          SIGN UP
It should probably be `LOG IN`...?

2024-02-22 22:15 UTC, rhysmah commented
I fetched your changes and rebased  this branch. Made your change. 

Let me know everything's okay, or if there are any issues. Once this is resolved, I have a PR for #74, and I'd love to get your feedback on that.

2024-02-23 08:23 UTC, toco-t approved these changes

2024-02-23 08:26 UTC, toco-t commented
It seems that the deployment failed after you pushed the last change. You should check the logs before merging your branch!

2024-02-23 17:16 UTC, merged